version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prisma:
    image: node:20-alpine
    working_dir: /workspace
    command: sh -c "apk add --no-cache bash git && npm i -g prisma@5 && tail -f /dev/null"
    volumes:
      - ./:/workspace
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

volumes:
  db_data:
